# Generated by Django 6.0.6 on 2026-07-03 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('source', models.CharField(choices=[('LinkedIn', 'LinkedIn'), ('Website', 'Website'), ('Referral', 'Referral'), ('Cold Call', 'Cold Call'), ('Event', 'Event'), ('Other', 'Other')], default='Website', max_length=50)),
                ('status', models.CharField(choices=[('New', 'New'), ('In Progress', 'In Progress'), ('Converted', 'Converted')], default='New', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
